(require "../cogs/strcase-core.scm")

(define (check label actual expected)
  (when (not (equal? actual expected))
    (error! (string-append label ": expected " expected ", got " actual))))

(check "snake from words" (strcase->snake "hello world") "hello_world")
(check "snake from camel" (strcase->snake "helloWorld") "hello_world")
(check "snake from acronym" (strcase->snake "HTTP response_code") "http_response_code")
(check "kebab" (strcase->kebab "hello_world") "hello-world")
(check "camel" (strcase->camel "hello_world") "helloWorld")
(check "camel from screaming snake" (strcase->camel "NON_ALPHANUMERIC") "nonAlphanumeric")
(check "pascal" (strcase->pascal "hello_world") "HelloWorld")
(check "pascal from screaming snake" (strcase->pascal "NON_ALPHANUMERIC") "NonAlphanumeric")
(check "screaming snake" (strcase->screaming-snake "hello-world") "HELLO_WORLD")
(check "snake from screaming snake" (strcase->snake "NON_ALPHANUMERIC") "non_alphanumeric")
(check "title" (strcase->title "hello_world") "Hello World")
(check "title from screaming snake" (strcase->title "NON_ALPHANUMERIC") "Non Alphanumeric")
(check "smart upper from snake initialism" (strcase->smart-case-upper "http_test") "HTTPTest")
(check "smart lower from snake initialism" (strcase->smart-case-lower "test_http") "testHTTP")
(check "smart lower first initialism" (strcase->smart-case-lower "http_test") "httpTest")
(check "smart upper from acronym" (strcase->smart-case-upper "HTTP response_code") "HTTPResponseCode")
(check "smart lower from id" (strcase->smart-case-lower "user_id") "userID")
(strcase-extend-smart-case-dictionary! (list "Haxe" "Http"))
(check "smart dictionary extend" (strcase->smart-case-upper "haxe_plugin") "HaxePlugin")
(check "smart dictionary override" (strcase->smart-case-upper "http_test") "HttpTest")
(strcase-set-smart-case-dictionary! (list "Api"))
(check "smart dictionary set replaces defaults" (strcase->smart-case-upper "http_api") "HttpApi")
